# Simulation paramters
path:
  path: 'params.yaml'

simulation:
  tot_sims: 1      # n' of simulations
  n_clients: 35    #number of clients
  n_rounds: 250     # 

# Parameters for the neural networks
model :
  id: "Sentiment" #[CNN,VGG,Sentiment] use Sentiment -- > for Stack-Overflow Sentiment dataset , Use CNN,VGG ---> for EMNSIT or CIFAR10 datasets
  epochs: 1
  batch_size: 32

  optimizer:
    type: 'SGD' # 'Adam','SGD'
    local_lr: 0.01 # Learning rate

# Parameters for the dataset and Algorithms
data:
  Algorithm: ['PER'] # [Fedprox,Scaffold,Ditto,VAN,LOC,pFedME,PER] (VAN = Federated Averaging, LOC = Local training, PER = our algorithm)
  dataset: 'Sentiment' # [Sentiment, EMNIST,CIFAR10]
  alpha : None

  PER:
    cluster_mode : "off" # ["on", "off"]  ##################  Relevant only for Algorithm : PER ######################
    divisor : 10 # 10 ( should be > 1) Defines the amount of data used by each device to calculate the variance to calculate the aggregation weights, equal to data_available/divisor

  Ditto:
    mu : 0.1

  Fedprox:
    mu: 0.001
    gamma : 0

  pFedMe:
    mu: 15
    R : 20
    K : 3
    local_etax : 0.01
    global_etax : 0.01

